### ISSUE TITLE
Light themes shows dark and light logo

### ISSUE THREAD

**Issue by dephiloper** [Coderdojo-Schoeneweide/coderdojo-schoeneweide.github.io#1]
Hello beautiful peeps, Philipp here ✌️ 
I noticed that when I launch the coderdojo-schoeneweide.github.io website the top banner (with the logo) shows up for both the dark and the light theme. After switching to dark and back to light the website shows only one banner.

<img width="1260" alt="Screenshot 2021-11-16 at 10 54 39" src="https://user-images.githubusercontent.com/19599410/141963454-79ef6e88-9e51-4c34-b223-7824fe8e2720.png">

This happens to me on chrome and safari, but **only when I visit the website for the first time** (I guess when no cookie is created for the preferred theme 🤷).

**Comment by Kaes3kuch3n** [comment]
Thanks, should be fixed now ^^
